[build]
  command = "npm install -g pnpm && pnpm install --no-frozen-lockfile && pnpm --filter @yacita/types build && pnpm --filter @yacita/utils build && pnpm --filter @yacita/web build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PRIVATE_TARGET = "server"

[[plugins]]
  package = "@netlify/plugin-nextjs"
