[build]
  command = "pnpm --filter @yacita/types build && pnpm --filter @yacita/utils build && pnpm --filter @yacita/web build"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
